version: '3.5'

networks:
  main:
    name: main-network

services:
  membership:
    networks:
      - main
    build: .
    container_name: Membership
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - POSTGRES_DATASOURCE_NAME=${POSTGRES_DATASOURCE_NAME}
    env_file:
      - ./.env
    ports:
      - 80:80
      