name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Fetch Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - 
      name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: waratep/rmasanglui:members-service-backend

  deploy:
    name: Deploy Service
    runs-on: ubuntu-latest
    needs: 
      - build
    env:
      SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
      REMOTE_HOST: ${{secrets.EC2_HOST}}
      REMOTE_USER: ${{secrets.EC2_USERNAME}}
      TARGET: ${{secrets.TARGET_DIR}}
    steps:
      - 
        name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.EC2_HOST}}
          REMOTE_USER: ${{secrets.EC2_USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}
    
      -
        name: Docker-Compose Deploy
        uses: alex-ac/github-action-ssh-docker-compose@master
        with:
          ssh_host: ${{ secrets.EC2_HOST }}
          ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
          ssh_user: ${{ secrets.EC2_USERNAME }}
          docker_compose_prefix: membership
          docker_compose_filename: ./docker-compose.yaml